services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus
    volumes:
      - nexus_pg_data:/var/lib/postgresql/data

volumes:
  nexus_pg_data:
